### PR TITLE
Updates for Mongoose 5

### PR DESCRIPTION
**Pull request by thxmike**
Updated dependencies to mongoose 5, bson 1 and uuid 1.4.8. 
Updated code to support the new namespace for bson.binary. UUID subtype
Updated test to support new namespace bson.binary. UUID subtype

### CODE REVIEW

**Comment by thxmike** [comment]
Rolled back Dev Dependancies since support is for an older version of nodejs

**Comment by thxmike** [comment]
Closing, will retry with .nvmrc file

**Comment by thxmike** [comment]
Not sure why CI system is not honoring .nvmrc file. I will continue to work off of fork, until I can investigate why. Perhaps the author may provide some insight.

**Comment by niahmiah** [comment]
@thxmike Look at the .travis.yml file for node version

I am ok with going to latest LTS

**Comment by thxmike** [comment]
Will do. I will spend some time working on this. Thanks

**Comment by thxmike** [comment]
Attempting changes to the .travis.yml file.

**Pull request merged**
